[mypy]
ignore_missing_imports = True
exclude = (?x)(
    # Exclude protobuf generated files
    .*_pb2\.py$
    | .*_pb2_grpc\.py$
    # Exclude __pycache__ and other build artifacts
    | __pycache__
    | \.venv
    | build
    | dist
    )