# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kumiho_pb2 as kumiho__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kumiho_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KumihoServiceStub(object):
    """The Kumiho service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/kumiho.KumihoService/CreateProject',
                request_serializer=kumiho__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.GetProjects = channel.unary_unary(
                '/kumiho.KumihoService/GetProjects',
                request_serializer=kumiho__pb2.GetProjectsRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetProjectsResponse.FromString,
                _registered_method=True)
        self.UpdateProject = channel.unary_unary(
                '/kumiho.KumihoService/UpdateProject',
                request_serializer=kumiho__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/kumiho.KumihoService/DeleteProject',
                request_serializer=kumiho__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/kumiho.KumihoService/CreateGroup',
                request_serializer=kumiho__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.GetGroup = channel.unary_unary(
                '/kumiho.KumihoService/GetGroup',
                request_serializer=kumiho__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.GetChildGroups = channel.unary_unary(
                '/kumiho.KumihoService/GetChildGroups',
                request_serializer=kumiho__pb2.GetChildGroupsRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetChildGroupsResponse.FromString,
                _registered_method=True)
        self.DeleteGroup = channel.unary_unary(
                '/kumiho.KumihoService/DeleteGroup',
                request_serializer=kumiho__pb2.DeleteGroupRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateGroupMetadata = channel.unary_unary(
                '/kumiho.KumihoService/UpdateGroupMetadata',
                request_serializer=kumiho__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GroupResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/kumiho.KumihoService/CreateProduct',
                request_serializer=kumiho__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/kumiho.KumihoService/GetProduct',
                request_serializer=kumiho__pb2.GetProductRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProducts = channel.unary_unary(
                '/kumiho.KumihoService/GetProducts',
                request_serializer=kumiho__pb2.GetProductsRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetProductsResponse.FromString,
                _registered_method=True)
        self.ProductSearch = channel.unary_unary(
                '/kumiho.KumihoService/ProductSearch',
                request_serializer=kumiho__pb2.ProductSearchRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetProductsResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/kumiho.KumihoService/DeleteProduct',
                request_serializer=kumiho__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateProductMetadata = channel.unary_unary(
                '/kumiho.KumihoService/UpdateProductMetadata',
                request_serializer=kumiho__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.ResolveKref = channel.unary_unary(
                '/kumiho.KumihoService/ResolveKref',
                request_serializer=kumiho__pb2.ResolveKrefRequest.SerializeToString,
                response_deserializer=kumiho__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.ResolveLocation = channel.unary_unary(
                '/kumiho.KumihoService/ResolveLocation',
                request_serializer=kumiho__pb2.ResolveLocationRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ResolveLocationResponse.FromString,
                _registered_method=True)
        self.CreateVersion = channel.unary_unary(
                '/kumiho.KumihoService/CreateVersion',
                request_serializer=kumiho__pb2.CreateVersionRequest.SerializeToString,
                response_deserializer=kumiho__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/kumiho.KumihoService/GetVersion',
                request_serializer=kumiho__pb2.KrefRequest.SerializeToString,
                response_deserializer=kumiho__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.GetVersions = channel.unary_unary(
                '/kumiho.KumihoService/GetVersions',
                request_serializer=kumiho__pb2.GetVersionsRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetVersionsResponse.FromString,
                _registered_method=True)
        self.DeleteVersion = channel.unary_unary(
                '/kumiho.KumihoService/DeleteVersion',
                request_serializer=kumiho__pb2.DeleteVersionRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.PeekNextVersion = channel.unary_unary(
                '/kumiho.KumihoService/PeekNextVersion',
                request_serializer=kumiho__pb2.PeekNextVersionRequest.SerializeToString,
                response_deserializer=kumiho__pb2.PeekNextVersionResponse.FromString,
                _registered_method=True)
        self.UpdateVersionMetadata = channel.unary_unary(
                '/kumiho.KumihoService/UpdateVersionMetadata',
                request_serializer=kumiho__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=kumiho__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.TagVersion = channel.unary_unary(
                '/kumiho.KumihoService/TagVersion',
                request_serializer=kumiho__pb2.TagVersionRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UnTagVersion = channel.unary_unary(
                '/kumiho.KumihoService/UnTagVersion',
                request_serializer=kumiho__pb2.UnTagVersionRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.HasTag = channel.unary_unary(
                '/kumiho.KumihoService/HasTag',
                request_serializer=kumiho__pb2.HasTagRequest.SerializeToString,
                response_deserializer=kumiho__pb2.HasTagResponse.FromString,
                _registered_method=True)
        self.WasTagged = channel.unary_unary(
                '/kumiho.KumihoService/WasTagged',
                request_serializer=kumiho__pb2.WasTaggedRequest.SerializeToString,
                response_deserializer=kumiho__pb2.WasTaggedResponse.FromString,
                _registered_method=True)
        self.SetDefaultResource = channel.unary_unary(
                '/kumiho.KumihoService/SetDefaultResource',
                request_serializer=kumiho__pb2.SetDefaultResourceRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateResource = channel.unary_unary(
                '/kumiho.KumihoService/CreateResource',
                request_serializer=kumiho__pb2.CreateResourceRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/kumiho.KumihoService/GetResource',
                request_serializer=kumiho__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.GetResources = channel.unary_unary(
                '/kumiho.KumihoService/GetResources',
                request_serializer=kumiho__pb2.GetResourcesRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetResourcesResponse.FromString,
                _registered_method=True)
        self.GetResourcesByLocation = channel.unary_unary(
                '/kumiho.KumihoService/GetResourcesByLocation',
                request_serializer=kumiho__pb2.GetResourcesByLocationRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetResourcesByLocationResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/kumiho.KumihoService/DeleteResource',
                request_serializer=kumiho__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateResourceMetadata = channel.unary_unary(
                '/kumiho.KumihoService/UpdateResourceMetadata',
                request_serializer=kumiho__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=kumiho__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.CreateLink = channel.unary_unary(
                '/kumiho.KumihoService/CreateLink',
                request_serializer=kumiho__pb2.CreateLinkRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetLinks = channel.unary_unary(
                '/kumiho.KumihoService/GetLinks',
                request_serializer=kumiho__pb2.GetLinksRequest.SerializeToString,
                response_deserializer=kumiho__pb2.GetLinksResponse.FromString,
                _registered_method=True)
        self.DeleteLink = channel.unary_unary(
                '/kumiho.KumihoService/DeleteLink',
                request_serializer=kumiho__pb2.DeleteLinkRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetTenantUsage = channel.unary_unary(
                '/kumiho.KumihoService/GetTenantUsage',
                request_serializer=kumiho__pb2.GetTenantUsageRequest.SerializeToString,
                response_deserializer=kumiho__pb2.TenantUsageResponse.FromString,
                _registered_method=True)
        self.EventStream = channel.unary_stream(
                '/kumiho.KumihoService/EventStream',
                request_serializer=kumiho__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=kumiho__pb2.Event.FromString,
                _registered_method=True)
        self.SetDeprecated = channel.unary_unary(
                '/kumiho.KumihoService/SetDeprecated',
                request_serializer=kumiho__pb2.SetDeprecatedRequest.SerializeToString,
                response_deserializer=kumiho__pb2.StatusResponse.FromString,
                _registered_method=True)


class KumihoServiceServicer(object):
    """The Kumiho service definition.
    """

    def CreateProject(self, request, context):
        """Project methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Group methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroupMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Product methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProductSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveKref(self, request, context):
        """Version methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekNextVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVersionMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TagVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnTagVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WasTagged(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResource(self, request, context):
        """Resource methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourcesByLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResourceMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLink(self, request, context):
        """Link methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantUsage(self, request, context):
        """Tenant methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request, context):
        """Event Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDeprecated(self, request, context):
        """Deprecation methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KumihoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=kumiho__pb2.CreateProjectRequest.FromString,
                    response_serializer=kumiho__pb2.ProjectResponse.SerializeToString,
            ),
            'GetProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjects,
                    request_deserializer=kumiho__pb2.GetProjectsRequest.FromString,
                    response_serializer=kumiho__pb2.GetProjectsResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=kumiho__pb2.UpdateProjectRequest.FromString,
                    response_serializer=kumiho__pb2.ProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=kumiho__pb2.DeleteProjectRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=kumiho__pb2.CreateGroupRequest.FromString,
                    response_serializer=kumiho__pb2.GroupResponse.SerializeToString,
            ),
            'GetGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroup,
                    request_deserializer=kumiho__pb2.GetGroupRequest.FromString,
                    response_serializer=kumiho__pb2.GroupResponse.SerializeToString,
            ),
            'GetChildGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildGroups,
                    request_deserializer=kumiho__pb2.GetChildGroupsRequest.FromString,
                    response_serializer=kumiho__pb2.GetChildGroupsResponse.SerializeToString,
            ),
            'DeleteGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGroup,
                    request_deserializer=kumiho__pb2.DeleteGroupRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateGroupMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroupMetadata,
                    request_deserializer=kumiho__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=kumiho__pb2.GroupResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=kumiho__pb2.CreateProductRequest.FromString,
                    response_serializer=kumiho__pb2.ProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=kumiho__pb2.GetProductRequest.FromString,
                    response_serializer=kumiho__pb2.ProductResponse.SerializeToString,
            ),
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=kumiho__pb2.GetProductsRequest.FromString,
                    response_serializer=kumiho__pb2.GetProductsResponse.SerializeToString,
            ),
            'ProductSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProductSearch,
                    request_deserializer=kumiho__pb2.ProductSearchRequest.FromString,
                    response_serializer=kumiho__pb2.GetProductsResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=kumiho__pb2.DeleteProductRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateProductMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductMetadata,
                    request_deserializer=kumiho__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=kumiho__pb2.ProductResponse.SerializeToString,
            ),
            'ResolveKref': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveKref,
                    request_deserializer=kumiho__pb2.ResolveKrefRequest.FromString,
                    response_serializer=kumiho__pb2.VersionResponse.SerializeToString,
            ),
            'ResolveLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveLocation,
                    request_deserializer=kumiho__pb2.ResolveLocationRequest.FromString,
                    response_serializer=kumiho__pb2.ResolveLocationResponse.SerializeToString,
            ),
            'CreateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVersion,
                    request_deserializer=kumiho__pb2.CreateVersionRequest.FromString,
                    response_serializer=kumiho__pb2.VersionResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=kumiho__pb2.KrefRequest.FromString,
                    response_serializer=kumiho__pb2.VersionResponse.SerializeToString,
            ),
            'GetVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersions,
                    request_deserializer=kumiho__pb2.GetVersionsRequest.FromString,
                    response_serializer=kumiho__pb2.GetVersionsResponse.SerializeToString,
            ),
            'DeleteVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVersion,
                    request_deserializer=kumiho__pb2.DeleteVersionRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'PeekNextVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekNextVersion,
                    request_deserializer=kumiho__pb2.PeekNextVersionRequest.FromString,
                    response_serializer=kumiho__pb2.PeekNextVersionResponse.SerializeToString,
            ),
            'UpdateVersionMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVersionMetadata,
                    request_deserializer=kumiho__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=kumiho__pb2.VersionResponse.SerializeToString,
            ),
            'TagVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.TagVersion,
                    request_deserializer=kumiho__pb2.TagVersionRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'UnTagVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.UnTagVersion,
                    request_deserializer=kumiho__pb2.UnTagVersionRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'HasTag': grpc.unary_unary_rpc_method_handler(
                    servicer.HasTag,
                    request_deserializer=kumiho__pb2.HasTagRequest.FromString,
                    response_serializer=kumiho__pb2.HasTagResponse.SerializeToString,
            ),
            'WasTagged': grpc.unary_unary_rpc_method_handler(
                    servicer.WasTagged,
                    request_deserializer=kumiho__pb2.WasTaggedRequest.FromString,
                    response_serializer=kumiho__pb2.WasTaggedResponse.SerializeToString,
            ),
            'SetDefaultResource': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultResource,
                    request_deserializer=kumiho__pb2.SetDefaultResourceRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'CreateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResource,
                    request_deserializer=kumiho__pb2.CreateResourceRequest.FromString,
                    response_serializer=kumiho__pb2.ResourceResponse.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=kumiho__pb2.GetResourceRequest.FromString,
                    response_serializer=kumiho__pb2.ResourceResponse.SerializeToString,
            ),
            'GetResources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResources,
                    request_deserializer=kumiho__pb2.GetResourcesRequest.FromString,
                    response_serializer=kumiho__pb2.GetResourcesResponse.SerializeToString,
            ),
            'GetResourcesByLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourcesByLocation,
                    request_deserializer=kumiho__pb2.GetResourcesByLocationRequest.FromString,
                    response_serializer=kumiho__pb2.GetResourcesByLocationResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=kumiho__pb2.DeleteResourceRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateResourceMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResourceMetadata,
                    request_deserializer=kumiho__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=kumiho__pb2.ResourceResponse.SerializeToString,
            ),
            'CreateLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLink,
                    request_deserializer=kumiho__pb2.CreateLinkRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'GetLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinks,
                    request_deserializer=kumiho__pb2.GetLinksRequest.FromString,
                    response_serializer=kumiho__pb2.GetLinksResponse.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=kumiho__pb2.DeleteLinkRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
            'GetTenantUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantUsage,
                    request_deserializer=kumiho__pb2.GetTenantUsageRequest.FromString,
                    response_serializer=kumiho__pb2.TenantUsageResponse.SerializeToString,
            ),
            'EventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=kumiho__pb2.EventStreamRequest.FromString,
                    response_serializer=kumiho__pb2.Event.SerializeToString,
            ),
            'SetDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDeprecated,
                    request_deserializer=kumiho__pb2.SetDeprecatedRequest.FromString,
                    response_serializer=kumiho__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kumiho.KumihoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kumiho.KumihoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KumihoService(object):
    """The Kumiho service definition.
    """

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateProject',
            kumiho__pb2.CreateProjectRequest.SerializeToString,
            kumiho__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetProjects',
            kumiho__pb2.GetProjectsRequest.SerializeToString,
            kumiho__pb2.GetProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UpdateProject',
            kumiho__pb2.UpdateProjectRequest.SerializeToString,
            kumiho__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteProject',
            kumiho__pb2.DeleteProjectRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateGroup',
            kumiho__pb2.CreateGroupRequest.SerializeToString,
            kumiho__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetGroup',
            kumiho__pb2.GetGroupRequest.SerializeToString,
            kumiho__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetChildGroups',
            kumiho__pb2.GetChildGroupsRequest.SerializeToString,
            kumiho__pb2.GetChildGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteGroup',
            kumiho__pb2.DeleteGroupRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroupMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UpdateGroupMetadata',
            kumiho__pb2.UpdateMetadataRequest.SerializeToString,
            kumiho__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateProduct',
            kumiho__pb2.CreateProductRequest.SerializeToString,
            kumiho__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetProduct',
            kumiho__pb2.GetProductRequest.SerializeToString,
            kumiho__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetProducts',
            kumiho__pb2.GetProductsRequest.SerializeToString,
            kumiho__pb2.GetProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProductSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/ProductSearch',
            kumiho__pb2.ProductSearchRequest.SerializeToString,
            kumiho__pb2.GetProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteProduct',
            kumiho__pb2.DeleteProductRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UpdateProductMetadata',
            kumiho__pb2.UpdateMetadataRequest.SerializeToString,
            kumiho__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveKref(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/ResolveKref',
            kumiho__pb2.ResolveKrefRequest.SerializeToString,
            kumiho__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/ResolveLocation',
            kumiho__pb2.ResolveLocationRequest.SerializeToString,
            kumiho__pb2.ResolveLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateVersion',
            kumiho__pb2.CreateVersionRequest.SerializeToString,
            kumiho__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetVersion',
            kumiho__pb2.KrefRequest.SerializeToString,
            kumiho__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetVersions',
            kumiho__pb2.GetVersionsRequest.SerializeToString,
            kumiho__pb2.GetVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteVersion',
            kumiho__pb2.DeleteVersionRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekNextVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/PeekNextVersion',
            kumiho__pb2.PeekNextVersionRequest.SerializeToString,
            kumiho__pb2.PeekNextVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVersionMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UpdateVersionMetadata',
            kumiho__pb2.UpdateMetadataRequest.SerializeToString,
            kumiho__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TagVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/TagVersion',
            kumiho__pb2.TagVersionRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnTagVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UnTagVersion',
            kumiho__pb2.UnTagVersionRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/HasTag',
            kumiho__pb2.HasTagRequest.SerializeToString,
            kumiho__pb2.HasTagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WasTagged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/WasTagged',
            kumiho__pb2.WasTaggedRequest.SerializeToString,
            kumiho__pb2.WasTaggedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/SetDefaultResource',
            kumiho__pb2.SetDefaultResourceRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateResource',
            kumiho__pb2.CreateResourceRequest.SerializeToString,
            kumiho__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetResource',
            kumiho__pb2.GetResourceRequest.SerializeToString,
            kumiho__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetResources',
            kumiho__pb2.GetResourcesRequest.SerializeToString,
            kumiho__pb2.GetResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourcesByLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetResourcesByLocation',
            kumiho__pb2.GetResourcesByLocationRequest.SerializeToString,
            kumiho__pb2.GetResourcesByLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteResource',
            kumiho__pb2.DeleteResourceRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResourceMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/UpdateResourceMetadata',
            kumiho__pb2.UpdateMetadataRequest.SerializeToString,
            kumiho__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/CreateLink',
            kumiho__pb2.CreateLinkRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetLinks',
            kumiho__pb2.GetLinksRequest.SerializeToString,
            kumiho__pb2.GetLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/DeleteLink',
            kumiho__pb2.DeleteLinkRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/GetTenantUsage',
            kumiho__pb2.GetTenantUsageRequest.SerializeToString,
            kumiho__pb2.TenantUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kumiho.KumihoService/EventStream',
            kumiho__pb2.EventStreamRequest.SerializeToString,
            kumiho__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kumiho.KumihoService/SetDeprecated',
            kumiho__pb2.SetDeprecatedRequest.SerializeToString,
            kumiho__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
