# Sphinx configuration for the Kumiho Go SDK documentation.
#
# The API reference (api.md) is generated by gomarkdoc at build time; the
# narrative pages are hand-written. myst-parser renders the Markdown.

import re
from pathlib import Path

project = "Kumiho Go SDK"
copyright = "2026, kumihoclouds"
author = "kumihoclouds"

# Version comes from `const Version` in go/doc.go (the single source of truth).
_doc_go = (Path(__file__).resolve().parent.parent / "doc.go").read_text(encoding="utf-8")
_m = re.search(r'Version\s*=\s*"([^"]+)"', _doc_go)
release = _m.group(1) if _m else "0.0.0"
version = ".".join(release.split(".")[:2])

extensions = [
    "myst_parser",
]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "linkify",
]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "sphinx_rtd_theme"
html_title = f"Kumiho Go SDK {release}"

# gomarkdoc emits GitHub-flavored `[text](<#Anchor>)` links to headings myst
# can't always resolve as cross-references; the page still renders, so silence
# the (very noisy) xref + header warnings.
myst_heading_anchors = 3
suppress_warnings = ["myst.header", "myst.xref_missing"]
