// SPDX-License-Identifier: MIT
//
// MIT License
// Copyright (c) 2025 kumihoclouds
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: kumiho.proto

package kumihopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KumihoService_CreateProject_FullMethodName          = "/kumiho.KumihoService/CreateProject"
	KumihoService_GetProjects_FullMethodName            = "/kumiho.KumihoService/GetProjects"
	KumihoService_UpdateProject_FullMethodName          = "/kumiho.KumihoService/UpdateProject"
	KumihoService_DeleteProject_FullMethodName          = "/kumiho.KumihoService/DeleteProject"
	KumihoService_CreateSpace_FullMethodName            = "/kumiho.KumihoService/CreateSpace"
	KumihoService_GetSpace_FullMethodName               = "/kumiho.KumihoService/GetSpace"
	KumihoService_GetChildSpaces_FullMethodName         = "/kumiho.KumihoService/GetChildSpaces"
	KumihoService_DeleteSpace_FullMethodName            = "/kumiho.KumihoService/DeleteSpace"
	KumihoService_UpdateSpaceMetadata_FullMethodName    = "/kumiho.KumihoService/UpdateSpaceMetadata"
	KumihoService_CreateItem_FullMethodName             = "/kumiho.KumihoService/CreateItem"
	KumihoService_GetItem_FullMethodName                = "/kumiho.KumihoService/GetItem"
	KumihoService_GetItems_FullMethodName               = "/kumiho.KumihoService/GetItems"
	KumihoService_ItemSearch_FullMethodName             = "/kumiho.KumihoService/ItemSearch"
	KumihoService_DeleteItem_FullMethodName             = "/kumiho.KumihoService/DeleteItem"
	KumihoService_UpdateItemMetadata_FullMethodName     = "/kumiho.KumihoService/UpdateItemMetadata"
	KumihoService_Search_FullMethodName                 = "/kumiho.KumihoService/Search"
	KumihoService_ScoreRevisions_FullMethodName         = "/kumiho.KumihoService/ScoreRevisions"
	KumihoService_ResolveKref_FullMethodName            = "/kumiho.KumihoService/ResolveKref"
	KumihoService_ResolveLocation_FullMethodName        = "/kumiho.KumihoService/ResolveLocation"
	KumihoService_CreateRevision_FullMethodName         = "/kumiho.KumihoService/CreateRevision"
	KumihoService_GetRevision_FullMethodName            = "/kumiho.KumihoService/GetRevision"
	KumihoService_GetRevisions_FullMethodName           = "/kumiho.KumihoService/GetRevisions"
	KumihoService_BatchGetRevisions_FullMethodName      = "/kumiho.KumihoService/BatchGetRevisions"
	KumihoService_DeleteRevision_FullMethodName         = "/kumiho.KumihoService/DeleteRevision"
	KumihoService_PeekNextRevision_FullMethodName       = "/kumiho.KumihoService/PeekNextRevision"
	KumihoService_UpdateRevisionMetadata_FullMethodName = "/kumiho.KumihoService/UpdateRevisionMetadata"
	KumihoService_TagRevision_FullMethodName            = "/kumiho.KumihoService/TagRevision"
	KumihoService_UnTagRevision_FullMethodName          = "/kumiho.KumihoService/UnTagRevision"
	KumihoService_HasTag_FullMethodName                 = "/kumiho.KumihoService/HasTag"
	KumihoService_WasTagged_FullMethodName              = "/kumiho.KumihoService/WasTagged"
	KumihoService_SetDefaultArtifact_FullMethodName     = "/kumiho.KumihoService/SetDefaultArtifact"
	KumihoService_CreateArtifact_FullMethodName         = "/kumiho.KumihoService/CreateArtifact"
	KumihoService_GetArtifact_FullMethodName            = "/kumiho.KumihoService/GetArtifact"
	KumihoService_GetArtifacts_FullMethodName           = "/kumiho.KumihoService/GetArtifacts"
	KumihoService_GetArtifactsByLocation_FullMethodName = "/kumiho.KumihoService/GetArtifactsByLocation"
	KumihoService_DeleteArtifact_FullMethodName         = "/kumiho.KumihoService/DeleteArtifact"
	KumihoService_UpdateArtifactMetadata_FullMethodName = "/kumiho.KumihoService/UpdateArtifactMetadata"
	KumihoService_SetAttribute_FullMethodName           = "/kumiho.KumihoService/SetAttribute"
	KumihoService_GetAttribute_FullMethodName           = "/kumiho.KumihoService/GetAttribute"
	KumihoService_DeleteAttribute_FullMethodName        = "/kumiho.KumihoService/DeleteAttribute"
	KumihoService_CreateEdge_FullMethodName             = "/kumiho.KumihoService/CreateEdge"
	KumihoService_GetEdges_FullMethodName               = "/kumiho.KumihoService/GetEdges"
	KumihoService_DeleteEdge_FullMethodName             = "/kumiho.KumihoService/DeleteEdge"
	KumihoService_TraverseEdges_FullMethodName          = "/kumiho.KumihoService/TraverseEdges"
	KumihoService_FindShortestPath_FullMethodName       = "/kumiho.KumihoService/FindShortestPath"
	KumihoService_AnalyzeImpact_FullMethodName          = "/kumiho.KumihoService/AnalyzeImpact"
	KumihoService_CreateBundle_FullMethodName           = "/kumiho.KumihoService/CreateBundle"
	KumihoService_AddBundleMember_FullMethodName        = "/kumiho.KumihoService/AddBundleMember"
	KumihoService_RemoveBundleMember_FullMethodName     = "/kumiho.KumihoService/RemoveBundleMember"
	KumihoService_GetBundleMembers_FullMethodName       = "/kumiho.KumihoService/GetBundleMembers"
	KumihoService_GetBundleHistory_FullMethodName       = "/kumiho.KumihoService/GetBundleHistory"
	KumihoService_GetTenantUsage_FullMethodName         = "/kumiho.KumihoService/GetTenantUsage"
	KumihoService_EventStream_FullMethodName            = "/kumiho.KumihoService/EventStream"
	KumihoService_GetEventCapabilities_FullMethodName   = "/kumiho.KumihoService/GetEventCapabilities"
	KumihoService_SetDeprecated_FullMethodName          = "/kumiho.KumihoService/SetDeprecated"
)

// KumihoServiceClient is the client API for KumihoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Kumiho service definition.
type KumihoServiceClient interface {
	// Project methods
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Space methods
	CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error)
	GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error)
	GetChildSpaces(ctx context.Context, in *GetChildSpacesRequest, opts ...grpc.CallOption) (*GetChildSpacesResponse, error)
	DeleteSpace(ctx context.Context, in *DeleteSpaceRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateSpaceMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*SpaceResponse, error)
	// Item methods
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error)
	ItemSearch(ctx context.Context, in *ItemSearchRequest, opts ...grpc.CallOption) (*GetItemsResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateItemMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	// Full-text search (Google-like fuzzy search across items)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Score specific revisions against a query (server-side embeddings + fulltext)
	ScoreRevisions(ctx context.Context, in *ScoreRevisionsRequest, opts ...grpc.CallOption) (*ScoreRevisionsResponse, error)
	// Revision methods
	ResolveKref(ctx context.Context, in *ResolveKrefRequest, opts ...grpc.CallOption) (*RevisionResponse, error)
	ResolveLocation(ctx context.Context, in *ResolveLocationRequest, opts ...grpc.CallOption) (*ResolveLocationResponse, error)
	CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*RevisionResponse, error)
	GetRevision(ctx context.Context, in *KrefRequest, opts ...grpc.CallOption) (*RevisionResponse, error)
	GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error)
	BatchGetRevisions(ctx context.Context, in *BatchGetRevisionsRequest, opts ...grpc.CallOption) (*BatchGetRevisionsResponse, error)
	DeleteRevision(ctx context.Context, in *DeleteRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	PeekNextRevision(ctx context.Context, in *PeekNextRevisionRequest, opts ...grpc.CallOption) (*PeekNextRevisionResponse, error)
	UpdateRevisionMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*RevisionResponse, error)
	TagRevision(ctx context.Context, in *TagRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UnTagRevision(ctx context.Context, in *UnTagRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	HasTag(ctx context.Context, in *HasTagRequest, opts ...grpc.CallOption) (*HasTagResponse, error)
	WasTagged(ctx context.Context, in *WasTaggedRequest, opts ...grpc.CallOption) (*WasTaggedResponse, error)
	SetDefaultArtifact(ctx context.Context, in *SetDefaultArtifactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Artifact methods
	CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	GetArtifacts(ctx context.Context, in *GetArtifactsRequest, opts ...grpc.CallOption) (*GetArtifactsResponse, error)
	GetArtifactsByLocation(ctx context.Context, in *GetArtifactsByLocationRequest, opts ...grpc.CallOption) (*GetArtifactsByLocationResponse, error)
	DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateArtifactMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	// Attribute methods (granular metadata operations)
	// These work on any entity type (Revision, Item, Artifact, Space) identified by kref
	SetAttribute(ctx context.Context, in *SetAttributeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error)
	DeleteAttribute(ctx context.Context, in *DeleteAttributeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Edge methods
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Graph Traversal methods
	TraverseEdges(ctx context.Context, in *TraverseEdgesRequest, opts ...grpc.CallOption) (*TraverseEdgesResponse, error)
	FindShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error)
	AnalyzeImpact(ctx context.Context, in *ImpactAnalysisRequest, opts ...grpc.CallOption) (*ImpactAnalysisResponse, error)
	// Bundle methods
	CreateBundle(ctx context.Context, in *CreateBundleRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	AddBundleMember(ctx context.Context, in *AddBundleMemberRequest, opts ...grpc.CallOption) (*AddBundleMemberResponse, error)
	RemoveBundleMember(ctx context.Context, in *RemoveBundleMemberRequest, opts ...grpc.CallOption) (*RemoveBundleMemberResponse, error)
	GetBundleMembers(ctx context.Context, in *GetBundleMembersRequest, opts ...grpc.CallOption) (*GetBundleMembersResponse, error)
	GetBundleHistory(ctx context.Context, in *GetBundleHistoryRequest, opts ...grpc.CallOption) (*GetBundleHistoryResponse, error)
	// Tenant methods
	GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*TenantUsageResponse, error)
	// Event Streaming
	EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Get event streaming capabilities for the authenticated tenant's tier
	GetEventCapabilities(ctx context.Context, in *GetEventCapabilitiesRequest, opts ...grpc.CallOption) (*EventCapabilities, error)
	// Deprecation methods
	SetDeprecated(ctx context.Context, in *SetDeprecatedRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type kumihoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKumihoServiceClient(cc grpc.ClientConnInterface) KumihoServiceClient {
	return &kumihoServiceClient{cc}
}

func (c *kumihoServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, KumihoService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateSpace(ctx context.Context, in *CreateSpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetSpace(ctx context.Context, in *GetSpaceRequest, opts ...grpc.CallOption) (*SpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetChildSpaces(ctx context.Context, in *GetChildSpacesRequest, opts ...grpc.CallOption) (*GetChildSpacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChildSpacesResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetChildSpaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteSpace(ctx context.Context, in *DeleteSpaceRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UpdateSpaceMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*SpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceResponse)
	err := c.cc.Invoke(ctx, KumihoService_UpdateSpaceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) ItemSearch(ctx context.Context, in *ItemSearchRequest, opts ...grpc.CallOption) (*GetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsResponse)
	err := c.cc.Invoke(ctx, KumihoService_ItemSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UpdateItemMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, KumihoService_UpdateItemMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, KumihoService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) ScoreRevisions(ctx context.Context, in *ScoreRevisionsRequest, opts ...grpc.CallOption) (*ScoreRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreRevisionsResponse)
	err := c.cc.Invoke(ctx, KumihoService_ScoreRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) ResolveKref(ctx context.Context, in *ResolveKrefRequest, opts ...grpc.CallOption) (*RevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionResponse)
	err := c.cc.Invoke(ctx, KumihoService_ResolveKref_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) ResolveLocation(ctx context.Context, in *ResolveLocationRequest, opts ...grpc.CallOption) (*ResolveLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveLocationResponse)
	err := c.cc.Invoke(ctx, KumihoService_ResolveLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*RevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetRevision(ctx context.Context, in *KrefRequest, opts ...grpc.CallOption) (*RevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionsResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) BatchGetRevisions(ctx context.Context, in *BatchGetRevisionsRequest, opts ...grpc.CallOption) (*BatchGetRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetRevisionsResponse)
	err := c.cc.Invoke(ctx, KumihoService_BatchGetRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteRevision(ctx context.Context, in *DeleteRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) PeekNextRevision(ctx context.Context, in *PeekNextRevisionRequest, opts ...grpc.CallOption) (*PeekNextRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeekNextRevisionResponse)
	err := c.cc.Invoke(ctx, KumihoService_PeekNextRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UpdateRevisionMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*RevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionResponse)
	err := c.cc.Invoke(ctx, KumihoService_UpdateRevisionMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) TagRevision(ctx context.Context, in *TagRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_TagRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UnTagRevision(ctx context.Context, in *UnTagRevisionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_UnTagRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) HasTag(ctx context.Context, in *HasTagRequest, opts ...grpc.CallOption) (*HasTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasTagResponse)
	err := c.cc.Invoke(ctx, KumihoService_HasTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) WasTagged(ctx context.Context, in *WasTaggedRequest, opts ...grpc.CallOption) (*WasTaggedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WasTaggedResponse)
	err := c.cc.Invoke(ctx, KumihoService_WasTagged_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) SetDefaultArtifact(ctx context.Context, in *SetDefaultArtifactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_SetDefaultArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetArtifacts(ctx context.Context, in *GetArtifactsRequest, opts ...grpc.CallOption) (*GetArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactsResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetArtifactsByLocation(ctx context.Context, in *GetArtifactsByLocationRequest, opts ...grpc.CallOption) (*GetArtifactsByLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactsByLocationResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetArtifactsByLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) UpdateArtifactMetadata(ctx context.Context, in *UpdateMetadataRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, KumihoService_UpdateArtifactMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) SetAttribute(ctx context.Context, in *SetAttributeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_SetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributeResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteAttribute(ctx context.Context, in *DeleteAttributeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgesResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) TraverseEdges(ctx context.Context, in *TraverseEdgesRequest, opts ...grpc.CallOption) (*TraverseEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraverseEdgesResponse)
	err := c.cc.Invoke(ctx, KumihoService_TraverseEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) FindShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortestPathResponse)
	err := c.cc.Invoke(ctx, KumihoService_FindShortestPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) AnalyzeImpact(ctx context.Context, in *ImpactAnalysisRequest, opts ...grpc.CallOption) (*ImpactAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpactAnalysisResponse)
	err := c.cc.Invoke(ctx, KumihoService_AnalyzeImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) CreateBundle(ctx context.Context, in *CreateBundleRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, KumihoService_CreateBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) AddBundleMember(ctx context.Context, in *AddBundleMemberRequest, opts ...grpc.CallOption) (*AddBundleMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBundleMemberResponse)
	err := c.cc.Invoke(ctx, KumihoService_AddBundleMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) RemoveBundleMember(ctx context.Context, in *RemoveBundleMemberRequest, opts ...grpc.CallOption) (*RemoveBundleMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBundleMemberResponse)
	err := c.cc.Invoke(ctx, KumihoService_RemoveBundleMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetBundleMembers(ctx context.Context, in *GetBundleMembersRequest, opts ...grpc.CallOption) (*GetBundleMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBundleMembersResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetBundleMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetBundleHistory(ctx context.Context, in *GetBundleHistoryRequest, opts ...grpc.CallOption) (*GetBundleHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBundleHistoryResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetBundleHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*TenantUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantUsageResponse)
	err := c.cc.Invoke(ctx, KumihoService_GetTenantUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) EventStream(ctx context.Context, in *EventStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KumihoService_ServiceDesc.Streams[0], KumihoService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventStreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KumihoService_EventStreamClient = grpc.ServerStreamingClient[Event]

func (c *kumihoServiceClient) GetEventCapabilities(ctx context.Context, in *GetEventCapabilitiesRequest, opts ...grpc.CallOption) (*EventCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventCapabilities)
	err := c.cc.Invoke(ctx, KumihoService_GetEventCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kumihoServiceClient) SetDeprecated(ctx context.Context, in *SetDeprecatedRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KumihoService_SetDeprecated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KumihoServiceServer is the server API for KumihoService service.
// All implementations must embed UnimplementedKumihoServiceServer
// for forward compatibility.
//
// The Kumiho service definition.
type KumihoServiceServer interface {
	// Project methods
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*StatusResponse, error)
	// Space methods
	CreateSpace(context.Context, *CreateSpaceRequest) (*SpaceResponse, error)
	GetSpace(context.Context, *GetSpaceRequest) (*SpaceResponse, error)
	GetChildSpaces(context.Context, *GetChildSpacesRequest) (*GetChildSpacesResponse, error)
	DeleteSpace(context.Context, *DeleteSpaceRequest) (*StatusResponse, error)
	UpdateSpaceMetadata(context.Context, *UpdateMetadataRequest) (*SpaceResponse, error)
	// Item methods
	CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error)
	GetItem(context.Context, *GetItemRequest) (*ItemResponse, error)
	GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error)
	ItemSearch(context.Context, *ItemSearchRequest) (*GetItemsResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*StatusResponse, error)
	UpdateItemMetadata(context.Context, *UpdateMetadataRequest) (*ItemResponse, error)
	// Full-text search (Google-like fuzzy search across items)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Score specific revisions against a query (server-side embeddings + fulltext)
	ScoreRevisions(context.Context, *ScoreRevisionsRequest) (*ScoreRevisionsResponse, error)
	// Revision methods
	ResolveKref(context.Context, *ResolveKrefRequest) (*RevisionResponse, error)
	ResolveLocation(context.Context, *ResolveLocationRequest) (*ResolveLocationResponse, error)
	CreateRevision(context.Context, *CreateRevisionRequest) (*RevisionResponse, error)
	GetRevision(context.Context, *KrefRequest) (*RevisionResponse, error)
	GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error)
	BatchGetRevisions(context.Context, *BatchGetRevisionsRequest) (*BatchGetRevisionsResponse, error)
	DeleteRevision(context.Context, *DeleteRevisionRequest) (*StatusResponse, error)
	PeekNextRevision(context.Context, *PeekNextRevisionRequest) (*PeekNextRevisionResponse, error)
	UpdateRevisionMetadata(context.Context, *UpdateMetadataRequest) (*RevisionResponse, error)
	TagRevision(context.Context, *TagRevisionRequest) (*StatusResponse, error)
	UnTagRevision(context.Context, *UnTagRevisionRequest) (*StatusResponse, error)
	HasTag(context.Context, *HasTagRequest) (*HasTagResponse, error)
	WasTagged(context.Context, *WasTaggedRequest) (*WasTaggedResponse, error)
	SetDefaultArtifact(context.Context, *SetDefaultArtifactRequest) (*StatusResponse, error)
	// Artifact methods
	CreateArtifact(context.Context, *CreateArtifactRequest) (*ArtifactResponse, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*ArtifactResponse, error)
	GetArtifacts(context.Context, *GetArtifactsRequest) (*GetArtifactsResponse, error)
	GetArtifactsByLocation(context.Context, *GetArtifactsByLocationRequest) (*GetArtifactsByLocationResponse, error)
	DeleteArtifact(context.Context, *DeleteArtifactRequest) (*StatusResponse, error)
	UpdateArtifactMetadata(context.Context, *UpdateMetadataRequest) (*ArtifactResponse, error)
	// Attribute methods (granular metadata operations)
	// These work on any entity type (Revision, Item, Artifact, Space) identified by kref
	SetAttribute(context.Context, *SetAttributeRequest) (*StatusResponse, error)
	GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error)
	DeleteAttribute(context.Context, *DeleteAttributeRequest) (*StatusResponse, error)
	// Edge methods
	CreateEdge(context.Context, *CreateEdgeRequest) (*StatusResponse, error)
	GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*StatusResponse, error)
	// Graph Traversal methods
	TraverseEdges(context.Context, *TraverseEdgesRequest) (*TraverseEdgesResponse, error)
	FindShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error)
	AnalyzeImpact(context.Context, *ImpactAnalysisRequest) (*ImpactAnalysisResponse, error)
	// Bundle methods
	CreateBundle(context.Context, *CreateBundleRequest) (*ItemResponse, error)
	AddBundleMember(context.Context, *AddBundleMemberRequest) (*AddBundleMemberResponse, error)
	RemoveBundleMember(context.Context, *RemoveBundleMemberRequest) (*RemoveBundleMemberResponse, error)
	GetBundleMembers(context.Context, *GetBundleMembersRequest) (*GetBundleMembersResponse, error)
	GetBundleHistory(context.Context, *GetBundleHistoryRequest) (*GetBundleHistoryResponse, error)
	// Tenant methods
	GetTenantUsage(context.Context, *GetTenantUsageRequest) (*TenantUsageResponse, error)
	// Event Streaming
	EventStream(*EventStreamRequest, grpc.ServerStreamingServer[Event]) error
	// Get event streaming capabilities for the authenticated tenant's tier
	GetEventCapabilities(context.Context, *GetEventCapabilitiesRequest) (*EventCapabilities, error)
	// Deprecation methods
	SetDeprecated(context.Context, *SetDeprecatedRequest) (*StatusResponse, error)
	mustEmbedUnimplementedKumihoServiceServer()
}

// UnimplementedKumihoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKumihoServiceServer struct{}

func (UnimplementedKumihoServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedKumihoServiceServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedKumihoServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedKumihoServiceServer) CreateSpace(context.Context, *CreateSpaceRequest) (*SpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpace not implemented")
}
func (UnimplementedKumihoServiceServer) GetSpace(context.Context, *GetSpaceRequest) (*SpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpace not implemented")
}
func (UnimplementedKumihoServiceServer) GetChildSpaces(context.Context, *GetChildSpacesRequest) (*GetChildSpacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChildSpaces not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteSpace(context.Context, *DeleteSpaceRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSpace not implemented")
}
func (UnimplementedKumihoServiceServer) UpdateSpaceMetadata(context.Context, *UpdateMetadataRequest) (*SpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSpaceMetadata not implemented")
}
func (UnimplementedKumihoServiceServer) CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedKumihoServiceServer) GetItem(context.Context, *GetItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedKumihoServiceServer) GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedKumihoServiceServer) ItemSearch(context.Context, *ItemSearchRequest) (*GetItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ItemSearch not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedKumihoServiceServer) UpdateItemMetadata(context.Context, *UpdateMetadataRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemMetadata not implemented")
}
func (UnimplementedKumihoServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedKumihoServiceServer) ScoreRevisions(context.Context, *ScoreRevisionsRequest) (*ScoreRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreRevisions not implemented")
}
func (UnimplementedKumihoServiceServer) ResolveKref(context.Context, *ResolveKrefRequest) (*RevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveKref not implemented")
}
func (UnimplementedKumihoServiceServer) ResolveLocation(context.Context, *ResolveLocationRequest) (*ResolveLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveLocation not implemented")
}
func (UnimplementedKumihoServiceServer) CreateRevision(context.Context, *CreateRevisionRequest) (*RevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRevision not implemented")
}
func (UnimplementedKumihoServiceServer) GetRevision(context.Context, *KrefRequest) (*RevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevision not implemented")
}
func (UnimplementedKumihoServiceServer) GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevisions not implemented")
}
func (UnimplementedKumihoServiceServer) BatchGetRevisions(context.Context, *BatchGetRevisionsRequest) (*BatchGetRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetRevisions not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteRevision(context.Context, *DeleteRevisionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRevision not implemented")
}
func (UnimplementedKumihoServiceServer) PeekNextRevision(context.Context, *PeekNextRevisionRequest) (*PeekNextRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeekNextRevision not implemented")
}
func (UnimplementedKumihoServiceServer) UpdateRevisionMetadata(context.Context, *UpdateMetadataRequest) (*RevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRevisionMetadata not implemented")
}
func (UnimplementedKumihoServiceServer) TagRevision(context.Context, *TagRevisionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TagRevision not implemented")
}
func (UnimplementedKumihoServiceServer) UnTagRevision(context.Context, *UnTagRevisionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnTagRevision not implemented")
}
func (UnimplementedKumihoServiceServer) HasTag(context.Context, *HasTagRequest) (*HasTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasTag not implemented")
}
func (UnimplementedKumihoServiceServer) WasTagged(context.Context, *WasTaggedRequest) (*WasTaggedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WasTagged not implemented")
}
func (UnimplementedKumihoServiceServer) SetDefaultArtifact(context.Context, *SetDefaultArtifactRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultArtifact not implemented")
}
func (UnimplementedKumihoServiceServer) CreateArtifact(context.Context, *CreateArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArtifact not implemented")
}
func (UnimplementedKumihoServiceServer) GetArtifact(context.Context, *GetArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifact not implemented")
}
func (UnimplementedKumihoServiceServer) GetArtifacts(context.Context, *GetArtifactsRequest) (*GetArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifacts not implemented")
}
func (UnimplementedKumihoServiceServer) GetArtifactsByLocation(context.Context, *GetArtifactsByLocationRequest) (*GetArtifactsByLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifactsByLocation not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteArtifact(context.Context, *DeleteArtifactRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtifact not implemented")
}
func (UnimplementedKumihoServiceServer) UpdateArtifactMetadata(context.Context, *UpdateMetadataRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArtifactMetadata not implemented")
}
func (UnimplementedKumihoServiceServer) SetAttribute(context.Context, *SetAttributeRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAttribute not implemented")
}
func (UnimplementedKumihoServiceServer) GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttribute not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteAttribute(context.Context, *DeleteAttributeRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAttribute not implemented")
}
func (UnimplementedKumihoServiceServer) CreateEdge(context.Context, *CreateEdgeRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedKumihoServiceServer) GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdges not implemented")
}
func (UnimplementedKumihoServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedKumihoServiceServer) TraverseEdges(context.Context, *TraverseEdgesRequest) (*TraverseEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TraverseEdges not implemented")
}
func (UnimplementedKumihoServiceServer) FindShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindShortestPath not implemented")
}
func (UnimplementedKumihoServiceServer) AnalyzeImpact(context.Context, *ImpactAnalysisRequest) (*ImpactAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImpact not implemented")
}
func (UnimplementedKumihoServiceServer) CreateBundle(context.Context, *CreateBundleRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBundle not implemented")
}
func (UnimplementedKumihoServiceServer) AddBundleMember(context.Context, *AddBundleMemberRequest) (*AddBundleMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBundleMember not implemented")
}
func (UnimplementedKumihoServiceServer) RemoveBundleMember(context.Context, *RemoveBundleMemberRequest) (*RemoveBundleMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBundleMember not implemented")
}
func (UnimplementedKumihoServiceServer) GetBundleMembers(context.Context, *GetBundleMembersRequest) (*GetBundleMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBundleMembers not implemented")
}
func (UnimplementedKumihoServiceServer) GetBundleHistory(context.Context, *GetBundleHistoryRequest) (*GetBundleHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBundleHistory not implemented")
}
func (UnimplementedKumihoServiceServer) GetTenantUsage(context.Context, *GetTenantUsageRequest) (*TenantUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantUsage not implemented")
}
func (UnimplementedKumihoServiceServer) EventStream(*EventStreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedKumihoServiceServer) GetEventCapabilities(context.Context, *GetEventCapabilitiesRequest) (*EventCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventCapabilities not implemented")
}
func (UnimplementedKumihoServiceServer) SetDeprecated(context.Context, *SetDeprecatedRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeprecated not implemented")
}
func (UnimplementedKumihoServiceServer) mustEmbedUnimplementedKumihoServiceServer() {}
func (UnimplementedKumihoServiceServer) testEmbeddedByValue()                       {}

// UnsafeKumihoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KumihoServiceServer will
// result in compilation errors.
type UnsafeKumihoServiceServer interface {
	mustEmbedUnimplementedKumihoServiceServer()
}

func RegisterKumihoServiceServer(s grpc.ServiceRegistrar, srv KumihoServiceServer) {
	// If the following call panics, it indicates UnimplementedKumihoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KumihoService_ServiceDesc, srv)
}

func _KumihoService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateSpace(ctx, req.(*CreateSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetSpace(ctx, req.(*GetSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetChildSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetChildSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetChildSpaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetChildSpaces(ctx, req.(*GetChildSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteSpace(ctx, req.(*DeleteSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UpdateSpaceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UpdateSpaceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UpdateSpaceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UpdateSpaceMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetItems(ctx, req.(*GetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_ItemSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).ItemSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_ItemSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).ItemSearch(ctx, req.(*ItemSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UpdateItemMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UpdateItemMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UpdateItemMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UpdateItemMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_ScoreRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).ScoreRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_ScoreRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).ScoreRevisions(ctx, req.(*ScoreRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_ResolveKref_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveKrefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).ResolveKref(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_ResolveKref_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).ResolveKref(ctx, req.(*ResolveKrefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_ResolveLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).ResolveLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_ResolveLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).ResolveLocation(ctx, req.(*ResolveLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateRevision(ctx, req.(*CreateRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KrefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetRevision(ctx, req.(*KrefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetRevisions(ctx, req.(*GetRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_BatchGetRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).BatchGetRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_BatchGetRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).BatchGetRevisions(ctx, req.(*BatchGetRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteRevision(ctx, req.(*DeleteRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_PeekNextRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekNextRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).PeekNextRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_PeekNextRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).PeekNextRevision(ctx, req.(*PeekNextRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UpdateRevisionMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UpdateRevisionMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UpdateRevisionMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UpdateRevisionMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_TagRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).TagRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_TagRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).TagRevision(ctx, req.(*TagRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UnTagRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnTagRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UnTagRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UnTagRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UnTagRevision(ctx, req.(*UnTagRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_HasTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).HasTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_HasTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).HasTag(ctx, req.(*HasTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_WasTagged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WasTaggedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).WasTagged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_WasTagged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).WasTagged(ctx, req.(*WasTaggedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_SetDefaultArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).SetDefaultArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_SetDefaultArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).SetDefaultArtifact(ctx, req.(*SetDefaultArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateArtifact(ctx, req.(*CreateArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetArtifacts(ctx, req.(*GetArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetArtifactsByLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactsByLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetArtifactsByLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetArtifactsByLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetArtifactsByLocation(ctx, req.(*GetArtifactsByLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteArtifact(ctx, req.(*DeleteArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_UpdateArtifactMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).UpdateArtifactMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_UpdateArtifactMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).UpdateArtifactMetadata(ctx, req.(*UpdateMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_SetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).SetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_SetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).SetAttribute(ctx, req.(*SetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetAttribute(ctx, req.(*GetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteAttribute(ctx, req.(*DeleteAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetEdges(ctx, req.(*GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_TraverseEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraverseEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).TraverseEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_TraverseEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).TraverseEdges(ctx, req.(*TraverseEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_FindShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).FindShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_FindShortestPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).FindShortestPath(ctx, req.(*ShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_AnalyzeImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpactAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).AnalyzeImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_AnalyzeImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).AnalyzeImpact(ctx, req.(*ImpactAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_CreateBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).CreateBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_CreateBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).CreateBundle(ctx, req.(*CreateBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_AddBundleMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBundleMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).AddBundleMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_AddBundleMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).AddBundleMember(ctx, req.(*AddBundleMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_RemoveBundleMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBundleMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).RemoveBundleMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_RemoveBundleMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).RemoveBundleMember(ctx, req.(*RemoveBundleMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetBundleMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetBundleMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetBundleMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetBundleMembers(ctx, req.(*GetBundleMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetBundleHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundleHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetBundleHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetBundleHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetBundleHistory(ctx, req.(*GetBundleHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_GetTenantUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetTenantUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetTenantUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetTenantUsage(ctx, req.(*GetTenantUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KumihoServiceServer).EventStream(m, &grpc.GenericServerStream[EventStreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KumihoService_EventStreamServer = grpc.ServerStreamingServer[Event]

func _KumihoService_GetEventCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).GetEventCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_GetEventCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).GetEventCapabilities(ctx, req.(*GetEventCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KumihoService_SetDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeprecatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KumihoServiceServer).SetDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KumihoService_SetDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KumihoServiceServer).SetDeprecated(ctx, req.(*SetDeprecatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KumihoService_ServiceDesc is the grpc.ServiceDesc for KumihoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KumihoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kumiho.KumihoService",
	HandlerType: (*KumihoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _KumihoService_CreateProject_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _KumihoService_GetProjects_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _KumihoService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _KumihoService_DeleteProject_Handler,
		},
		{
			MethodName: "CreateSpace",
			Handler:    _KumihoService_CreateSpace_Handler,
		},
		{
			MethodName: "GetSpace",
			Handler:    _KumihoService_GetSpace_Handler,
		},
		{
			MethodName: "GetChildSpaces",
			Handler:    _KumihoService_GetChildSpaces_Handler,
		},
		{
			MethodName: "DeleteSpace",
			Handler:    _KumihoService_DeleteSpace_Handler,
		},
		{
			MethodName: "UpdateSpaceMetadata",
			Handler:    _KumihoService_UpdateSpaceMetadata_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _KumihoService_CreateItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _KumihoService_GetItem_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _KumihoService_GetItems_Handler,
		},
		{
			MethodName: "ItemSearch",
			Handler:    _KumihoService_ItemSearch_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _KumihoService_DeleteItem_Handler,
		},
		{
			MethodName: "UpdateItemMetadata",
			Handler:    _KumihoService_UpdateItemMetadata_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _KumihoService_Search_Handler,
		},
		{
			MethodName: "ScoreRevisions",
			Handler:    _KumihoService_ScoreRevisions_Handler,
		},
		{
			MethodName: "ResolveKref",
			Handler:    _KumihoService_ResolveKref_Handler,
		},
		{
			MethodName: "ResolveLocation",
			Handler:    _KumihoService_ResolveLocation_Handler,
		},
		{
			MethodName: "CreateRevision",
			Handler:    _KumihoService_CreateRevision_Handler,
		},
		{
			MethodName: "GetRevision",
			Handler:    _KumihoService_GetRevision_Handler,
		},
		{
			MethodName: "GetRevisions",
			Handler:    _KumihoService_GetRevisions_Handler,
		},
		{
			MethodName: "BatchGetRevisions",
			Handler:    _KumihoService_BatchGetRevisions_Handler,
		},
		{
			MethodName: "DeleteRevision",
			Handler:    _KumihoService_DeleteRevision_Handler,
		},
		{
			MethodName: "PeekNextRevision",
			Handler:    _KumihoService_PeekNextRevision_Handler,
		},
		{
			MethodName: "UpdateRevisionMetadata",
			Handler:    _KumihoService_UpdateRevisionMetadata_Handler,
		},
		{
			MethodName: "TagRevision",
			Handler:    _KumihoService_TagRevision_Handler,
		},
		{
			MethodName: "UnTagRevision",
			Handler:    _KumihoService_UnTagRevision_Handler,
		},
		{
			MethodName: "HasTag",
			Handler:    _KumihoService_HasTag_Handler,
		},
		{
			MethodName: "WasTagged",
			Handler:    _KumihoService_WasTagged_Handler,
		},
		{
			MethodName: "SetDefaultArtifact",
			Handler:    _KumihoService_SetDefaultArtifact_Handler,
		},
		{
			MethodName: "CreateArtifact",
			Handler:    _KumihoService_CreateArtifact_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _KumihoService_GetArtifact_Handler,
		},
		{
			MethodName: "GetArtifacts",
			Handler:    _KumihoService_GetArtifacts_Handler,
		},
		{
			MethodName: "GetArtifactsByLocation",
			Handler:    _KumihoService_GetArtifactsByLocation_Handler,
		},
		{
			MethodName: "DeleteArtifact",
			Handler:    _KumihoService_DeleteArtifact_Handler,
		},
		{
			MethodName: "UpdateArtifactMetadata",
			Handler:    _KumihoService_UpdateArtifactMetadata_Handler,
		},
		{
			MethodName: "SetAttribute",
			Handler:    _KumihoService_SetAttribute_Handler,
		},
		{
			MethodName: "GetAttribute",
			Handler:    _KumihoService_GetAttribute_Handler,
		},
		{
			MethodName: "DeleteAttribute",
			Handler:    _KumihoService_DeleteAttribute_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _KumihoService_CreateEdge_Handler,
		},
		{
			MethodName: "GetEdges",
			Handler:    _KumihoService_GetEdges_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _KumihoService_DeleteEdge_Handler,
		},
		{
			MethodName: "TraverseEdges",
			Handler:    _KumihoService_TraverseEdges_Handler,
		},
		{
			MethodName: "FindShortestPath",
			Handler:    _KumihoService_FindShortestPath_Handler,
		},
		{
			MethodName: "AnalyzeImpact",
			Handler:    _KumihoService_AnalyzeImpact_Handler,
		},
		{
			MethodName: "CreateBundle",
			Handler:    _KumihoService_CreateBundle_Handler,
		},
		{
			MethodName: "AddBundleMember",
			Handler:    _KumihoService_AddBundleMember_Handler,
		},
		{
			MethodName: "RemoveBundleMember",
			Handler:    _KumihoService_RemoveBundleMember_Handler,
		},
		{
			MethodName: "GetBundleMembers",
			Handler:    _KumihoService_GetBundleMembers_Handler,
		},
		{
			MethodName: "GetBundleHistory",
			Handler:    _KumihoService_GetBundleHistory_Handler,
		},
		{
			MethodName: "GetTenantUsage",
			Handler:    _KumihoService_GetTenantUsage_Handler,
		},
		{
			MethodName: "GetEventCapabilities",
			Handler:    _KumihoService_GetEventCapabilities_Handler,
		},
		{
			MethodName: "SetDeprecated",
			Handler:    _KumihoService_SetDeprecated_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _KumihoService_EventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kumiho.proto",
}
