# Configuration file for the Sphinx documentation builder.

from __future__ import annotations

import re
from pathlib import Path


def _extract_cmake_version(cmake_path: Path) -> str:
    text = cmake_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(
        r"project\([^\)]*\bVERSION\s+([0-9]+\.[0-9]+\.[0-9]+(?:[-+._a-zA-Z0-9]*)?)\b",
        text,
    )
    if not m:
        raise RuntimeError(f"Could not extract VERSION from {cmake_path}")
    return m.group(1)


# -- Project information -----------------------------------------------------

project = "Kumiho C++ SDK"
copyright = "2025, Kumiho Clouds"
author = "Kumiho Clouds"

_docs_dir = Path(__file__).resolve().parent
_root = _docs_dir.parent
release = _extract_cmake_version(_root / "CMakeLists.txt")
version = ".".join(release.split(".")[:2])


# -- General configuration ---------------------------------------------------

extensions = [
    "breathe",
    "myst_parser",
]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
master_doc = "index"


# -- Breathe / Doxygen -------------------------------------------------------

# Doxygen XML is generated by CI (see docs/Doxyfile.sphinx) into:
#   docs/_build/doxygen/xml
breathe_projects = {
    "kumiho": str(_docs_dir / "_build" / "doxygen" / "xml"),
}
breathe_default_project = "kumiho"


# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_title = f"{project} v{release}"

html_theme_options = {
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

html_sidebars = {
    "**": [
        "relations.html",
        "searchbox.html",
    ]
}
